Migrate !wrote to /wrote
cwarwicker/discord-Writer-Bot pull request #114
Opened 2022-01-04 11:24 UTC by Starlight220

The syntax is a bit annoying, and it's really easy to have the `project` argument be missed.
We can make it required (and then it won't be missed), but then it'll be a problem for using the command without a project.
Ideas?

2022-01-07 17:48 UTC, cwarwicker requested changes
I think this is okay for now. When we move to v4, we can improve the way project name is selected hopefully, with autocomplete.

Can you just go through and format things the same as the others, with the defer and the comments, etc...

2022-01-07 17:48 UTC, cwarwicker commented on cogs/writing/wrote.py
> +                       connector={"project": "shortname"})
What is this connector for?

2022-01-07 17:48 UTC, cwarwicker commented on cogs/writing/wrote.py
> +    @commands.command(name="wrote")
Can you format this like the other ones we've been doing lately?

2022-01-09 15:11 UTC, Starlight220 commented on cogs/writing/wrote.py
> +                       connector={"project": "shortname"})
so that the displayed parameter name is `project` but the python method parameter is named `shortname`. There was already a `project` variable and I wanted to avoid renaming stuff.

2022-01-09 15:12 UTC, Starlight220 commented on cogs/writing/wrote.py
> +    @commands.command(name="wrote")
Done

2022-01-11 18:00 UTC, cwarwicker commented
You can remove the `self._arguments` and the `from structures.wrapper import CommandWrapper` as they aren't needed any more.

Also "Shortname of the project you're sprinting in" should be changed, as this isn't a sprint, so shouldn't reference them. Just "Shortname of the project" should be fine.

2022-01-12 22:44 UTC, Starlight220 commented
Fixed.

2022-01-14 15:24 UTC, merged