Migrate sprint to slash command
cwarwicker/discord-Writer-Bot pull request #119
Opened 2022-01-06 19:45 UTC by Starlight220

This is the big one.

The syntax is going to have to change, so if there are any requests/comments feel free to comment here or on the support Discord server.

2022-01-14 16:24 UTC, cwarwicker requested changes
There are some places where your editor has moved things onto a new line because the line was long, but it looks quite odd in some places. Could you have a general tidy up of formatting as well, please.

2022-01-14 16:24 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        project_options = [
One potential issue (not sure how big of a deal) is that if you do:

(Assuming you have 1 project with shortname `valid`)

`sprint join project:valid` You get the dropdown saying you can change it,  with `valid` selected.
If you then do an invalid one, e.g. `sprint join project:invalid` the dropdown is then blank and doesn't have a project selected, even though you are still sprinting in project `valid`. So, it should probably check what what you are sprinting in and show that, in that case.

2022-01-14 16:24 UTC, cwarwicker commented on cogs/writing/sprint.py
> +    @cog_ext.cog_subcommand(
One thing which will need adding in, is making sure the user sprint type is correct on join.

E.g. if i join as a non-wc user, then run join again as a normal user with a starting wc, it says i'm a non-wc user. So, updating the type when we run join should fix that.

2022-01-14 16:24 UTC, cwarwicker commented on cogs/writing/sprint.py
> +    async def sprint_status(self, context: SlashContext):
Should we add the name of the project being sprinted in, to the status command? If they are sprinting in one.

2022-01-14 16:24 UTC, cwarwicker commented on cogs/writing/sprint.py
> +            message += lib.get_string('sprint:notified', user.get_guild())
This string current says to run `sprint forget` to be unnotified. That will need changing.

2022-01-16 11:36 UTC, Starlight220 commented on cogs/writing/sprint.py
> +        if sprint.is_finished():
It shouldn't have been removed.

2022-01-16 22:51 UTC, Starlight220 commented on cogs/writing/sprint.py
> +    @cog_ext.cog_subcommand(
I think that I checked that, but it can be made sure of.

2022-01-16 22:52 UTC, Starlight220 commented on cogs/writing/sprint.py
> +                required=True,
Requiring an explicit 0-join would improve the UX for everyone, and shouldn't be that much of a problem for those joining with 0.

2022-01-24 08:07 UTC, Starlight220 commented on cogs/writing/sprint.py
> +    async def sprint_status(self, context: SlashContext):
I'm not sure if I would include the project as part of the sprint's "status".
In any case, I think that this command is so rarely used that it's beside the point. That's definitely something that should be checked with usage reporting (once implemented).

2022-01-24 08:09 UTC, Starlight220 commented on cogs/writing/sprint.py
> +        project_options = [
The message will indicate which project you're sprinting in anyway; I'm not sure how helpful the dropdown is in general.

2022-01-28 14:28 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        if not Guild(context.guild_id).is_command_enabled('sprint'):
This is causing an error:

```
An exception has occurred while executing command `sprint`:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord_slash/client.py", line 1352, in invoke_command
    await func.invoke(ctx, **args)
  File "/usr/local/lib/python3.8/dist-packages/discord_slash/model.py", line 209, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "/app/cogs/writing/sprint.py", line 437, in sprint_end
    user, sprint, err = await SprintCommand._common_init(context)
  File "/app/cogs/writing/sprint.py", line 749, in _common_init
    if not Guild(context.guild_id).is_command_enabled('sprint'):
  File "/app/structures/guild.py", line 15, in __init__
    self._id = guild.id
AttributeError: 'int' object has no attribute 'id'
```

As Guild() expects an object, not an int.

2022-01-28 14:29 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        if not Guild(context.guild_id).is_command_enabled('sprint'):
Same as other comment, on this line as well.

2022-01-28 14:30 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        if not Guild(context.guild_id).is_command_enabled('sprint'):
And here

2022-01-28 14:30 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        if not Guild(context.guild_id).is_command_enabled('sprint'):
and here

2022-01-28 14:31 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        if not Guild(context.guild_id).is_command_enabled('sprint'):
and here

2022-01-28 14:45 UTC, cwarwicker commented on cogs/writing/sprint.py
> +        description="Declare words written this sprint",
I think we'll need a more detailed description for `wc` and `wrote` so people understand the difference in what they do.

2022-01-28 14:46 UTC, cwarwicker requested changes
See comments on individual lines

2022-02-18 10:39 UTC, merged