Moved all fun commands into 1 cog
cwarwicker/discord-Writer-Bot pull request #126
Opened 2022-01-09 13:49 UTC by cwarwicker

2022-01-09 14:40 UTC, Starlight220 requested changes
Other than those reviews, looks good overall. Do we want to move `fun.py` up and delete the `/fun/` folder, now that it only has one file?

2022-01-09 14:40 UTC, Starlight220 commented on cogs/fun/fun.py
> +                option_type=SlashCommandOptionType.STRING,
Should be `SlashCommandOptionType.USER`? This will remove the need for argument verification, as you get a `discord.abc.User` object on which you can use the `user.mention` property.

2022-01-09 14:40 UTC, Starlight220 commented on cogs/fun/fun.py
> +    bot.add_cog(Fun(bot))
git likes a newline at eof.

2022-01-09 14:40 UTC, Starlight220 commented on cogs/fun/fun.py
> +    async def old(self, context):
is there a reason why can't all the old commands be registered on the same method? either by using `aliases` or multiple `@command` decorators?

and pls move the old command stuff to after the new slash command stuff?

2022-01-11 16:39 UTC, cwarwicker commented on cogs/fun/fun.py
> +                option_type=SlashCommandOptionType.STRING,
Done

2022-01-11 16:40 UTC, cwarwicker commented on cogs/fun/fun.py
> +    bot.add_cog(Fun(bot))
done

2022-01-11 16:42 UTC, cwarwicker commented on cogs/fun/fun.py
> +    async def old(self, context):
Moved them into 1 method with aliases. Multiple command decotrators doesn't work.

2022-01-11 16:49 UTC, merged