Migrate `challenge` to Slash command.
cwarwicker/discord-Writer-Bot pull request #137
Opened 2022-02-18 15:50 UTC by cwarwicker

2022-02-18 22:15 UTC, kilobyte-terabyte reviewed
overall LGTM; left some comments but of course take or leave them as you see fit!!

2022-02-18 22:15 UTC, kilobyte-terabyte commented on cogs/writing/challenge.py
> +                description="How many minutes should the challenge be for? (minimum: 5 mins, maximum: 60 mins)",
i'd suggest changing it so it reads "minimum: 5, maximum: 60" -- so people dont try to input "mins" as part of the command

2022-02-18 22:15 UTC, kilobyte-terabyte commented on cogs/writing/challenge.py
> +                    create_choice(DIFFICULTY_INSANE, 'Insane'),
would it make sense to include the WPMs here? like "Easy (10 wpm)" so people don't have to use the help command

2022-02-18 22:15 UTC, kilobyte-terabyte commented on cogs/writing/challenge.py
> +        # Run the start challenge.
```suggestion
        # Cancel the challenge
```

2022-02-18 22:15 UTC, kilobyte-terabyte commented on cogs/writing/challenge.py
> +        # Run the start challenge.
```suggestion
        # Complete the challenge
```

2022-02-18 22:15 UTC, kilobyte-terabyte commented on cogs/writing/challenge.py
> +                wpm = 60
I would also suggest making these WPMs constants (maybe even in a map, to avoid the elifs?)

2022-02-18 22:15 UTC, kilobyte-terabyte commented on data/lang/en.json
> +    "challenge:noactive": "You do not have an active challenge. Perhaps you should start one? `/challenge start`",
might make sense to update the command in french also ? though 100% understandable if you want that to be a separate PR

2022-02-19 16:58 UTC, Starlight220 requested changes
- `context.guild_id` and `author_id` are preferable over `guild.id` and `author.id`

- why the split into `run_` methods?

2022-02-20 15:47 UTC, cwarwicker commented on cogs/writing/challenge.py
> +                    create_choice(DIFFICULTY_INSANE, 'Insane'),
Changed this to make it a bit random, so its not the same wpm each time.

2022-02-20 15:49 UTC, cwarwicker commented on data/lang/en.json
> +    "challenge:noactive": "You do not have an active challenge. Perhaps you should start one? `/challenge start`",
That will need translating. I can't do it myself.

2022-02-20 16:01 UTC, merged