Add interchangeable for and in for sprint command
cwarwicker/discord-Writer-Bot pull request #68
Opened 2020-12-02 15:14 UTC by marvelman3284

Add feature #67

2020-12-30 18:16 UTC, cwarwicker commented
Hi,

I've checked this out and tried it on my local but it doesn't seem to work. Running `sprint in 5` for example, gives me 'invalid sprint command'.

Also, looking at the `opt2` variable, it looks like you could do `sprint in 5 now` which doesn't make any sense.

Can you have another look at this please?

2020-12-30 21:43 UTC, cwarwicker requested changes
Added a few comments for changes. Almost there I think.

2020-12-30 21:43 UTC, cwarwicker commented on cogs/writing/sprint.py
> +                    + lib.get_string("sprint:err:for:unknown", user.get_guild())
Can you add a new error message to the lang file, as this says the format should be `sprint for 20 in 5` whereas in this command it should be `sprint in 5 for 20`. So add another lang string eg. `sprint:err:in:unknown` and change the format of the error.

2020-12-30 21:43 UTC, cwarwicker commented on cogs/writing/sprint.py
> +                length = 20
Can you please use the constant for this, rather than hard-coding the value `20`. Should be `self.DEFAULT_LENGTH`

2020-12-31 15:51 UTC, marvelman3284 commented on cogs/writing/sprint.py
> +                    + lib.get_string("sprint:err:for:unknown", user.get_guild())
Done.

2020-12-31 15:51 UTC, marvelman3284 commented on cogs/writing/sprint.py
> +                length = 20
Done.

2020-12-31 22:44 UTC, cwarwicker approved these changes

2020-12-31 22:44 UTC, merged